<?php
// Tema presetleri - 20 adet, isimlere uygun ana renkler
return [
    1 => [
        'name' => 'Radyo Yol (Kırmızı)',
        'primary' => '#c92a2a',
        'primary_hover' => '#dc2626',
        'accent' => '#c92a2a',
    ],
    2 => [
        'name' => 'Neon Mavi',
        'primary' => '#2563eb',
        'primary_hover' => '#3b82f6',
        'accent' => '#60a5fa',
    ],
    3 => [
        'name' => 'Yeşil Canlı',
        'primary' => '#16a34a',
        'primary_hover' => '#22c55e',
        'accent' => '#22c55e',
    ],
    4 => [
        'name' => 'Mor Gece',
        'primary' => '#7c3aed',
        'primary_hover' => '#8b5cf6',
        'accent' => '#a78bfa',
    ],
    5 => [
        'name' => 'Turuncu Enerji',
        'primary' => '#ea580c',
        'primary_hover' => '#f97316',
        'accent' => '#fb923c',
    ],
    6 => [
        'name' => 'Siyah Gold',
        'primary' => '#F6C34F',
        'primary_hover' => '#FFD56A',
        'accent' => '#D9A441',
        'preview_header_bg' => '#1a1810',
        'preview_btn_bg' => '#F6C34F',
        'preview_accent' => '#D9A441',
        'header_bg' => 'linear-gradient(180deg, rgba(15,13,8,0.98), rgba(35,30,18,0.97))',
        'footer_bg' => 'rgba(15,13,8,0.98)',
        'bar_bg' => 'linear-gradient(180deg, rgba(18,15,10,0.98), rgba(35,30,18,0.97))',
    ],
    7 => [
        'name' => 'Pembe Gül',
        'primary' => '#db2777',
        'primary_hover' => '#ec4899',
        'accent' => '#f472b6',
    ],
    8 => [
        'name' => 'Cyan Okyanus',
        'primary' => '#0891b2',
        'primary_hover' => '#06b6d4',
        'accent' => '#22d3ee',
    ],
    9 => [
        'name' => 'Sarı Parlak',
        'primary' => '#eab308',
        'primary_hover' => '#facc15',
        'accent' => '#fde047',
    ],
    10 => [
        'name' => 'Bordo Şarap',
        'primary' => '#9f1239',
        'primary_hover' => '#be123c',
        'accent' => '#e11d48',
    ],
    11 => [
        'name' => 'Lacivert Gece',
        'primary' => '#1e3a8a',
        'primary_hover' => '#2563eb',
        'accent' => '#3b82f6',
    ],
    12 => [
        'name' => 'Turkuaz Tropik',
        'primary' => '#0d9488',
        'primary_hover' => '#14b8a6',
        'accent' => '#2dd4bf',
    ],
    13 => [
        'name' => 'Gri Klasik',
        'primary' => '#6b7280',
        'primary_hover' => '#9ca3af',
        'accent' => '#9ca3af',
    ],
    14 => [
        'name' => 'İndigo Derin',
        'primary' => '#4f46e5',
        'primary_hover' => '#6366f1',
        'accent' => '#818cf8',
    ],
    15 => [
        'name' => 'Kehribar Sıcak',
        'primary' => '#d97706',
        'primary_hover' => '#f59e0b',
        'accent' => '#fbbf24',
    ],
    16 => [
        'name' => 'Gül Kırmızısı',
        'primary' => '#e11d48',
        'primary_hover' => '#f43f5e',
        'accent' => '#fb7185',
    ],
    17 => [
        'name' => 'Zümrüt Yeşil',
        'primary' => '#059669',
        'primary_hover' => '#10b981',
        'accent' => '#34d399',
    ],
    18 => [
        'name' => 'Menekşe Mor',
        'primary' => '#6d28d9',
        'primary_hover' => '#7c3aed',
        'accent' => '#a78bfa',
    ],
    19 => [
        'name' => 'Gök Mavisi',
        'primary' => '#0284c7',
        'primary_hover' => '#0ea5e9',
        'accent' => '#38bdf8',
    ],
    20 => [
        'name' => 'Koyu Gri',
        'primary' => '#4b5563',
        'primary_hover' => '#6b7280',
        'accent' => '#9ca3af',
    ],
];
