<?php

return [
    1 => [
        'name' => 'Kırmızı Radyo',
        'primary' => '#ff0033',
        'primary_hover' => '#ff3355',
        'accent' => '#ff0033',
        'glow' => '#ff0033',
    ],
    16 => [
        'name' => 'Siyah Gold (VIP)',
        'primary' => '#F6C34F',
        'primary_hover' => '#FFD56A',
        'accent' => '#D9A441',
        'glow' => '#F6C34F',
        'header_bg' => 'linear-gradient(90deg, rgba(246,195,79,0.28), rgba(0,0,0,0.55))',
        'footer_bg' => 'rgba(246,195,79,0.12)',
    ],
    2 => [
        'name' => 'Neon Mavi',
        'primary' => '#2563eb',
        'primary_hover' => '#3b82f6',
        'accent' => '#60a5fa',
        'glow' => '#3b82f6',
    ],
    3 => [
        'name' => 'Yeşil Canlı',
        'primary' => '#16a34a',
        'primary_hover' => '#22c55e',
        'accent' => '#22c55e',
        'glow' => '#16a34a',
    ],
    4 => [
        'name' => 'Mor Gece',
        'primary' => '#7c3aed',
        'primary_hover' => '#8b5cf6',
        'accent' => '#a78bfa',
        'glow' => '#7c3aed',
    ],
    5 => [
        'name' => 'Turuncu Enerji',
        'primary' => '#ea580c',
        'primary_hover' => '#f97316',
        'accent' => '#fb923c',
        'glow' => '#ea580c',
    ],
    6 => [
        'name' => 'Pembe Neon',
        'primary' => '#db2777',
        'primary_hover' => '#ec4899',
        'accent' => '#f472b6',
        'glow' => '#db2777',
    ],
    7 => [
        'name' => 'Cyan Okyanus',
        'primary' => '#0891b2',
        'primary_hover' => '#06b6d4',
        'accent' => '#22d3ee',
        'glow' => '#0891b2',
    ],
    8 => [
        'name' => 'Amber Altın',
        'primary' => '#d97706',
        'primary_hover' => '#f59e0b',
        'accent' => '#fbbf24',
        'glow' => '#d97706',
    ],
    9 => [
        'name' => 'Koyu Kırmızı',
        'primary' => '#b91c1c',
        'primary_hover' => '#dc2626',
        'accent' => '#c92a2a',
        'glow' => '#b91c1c',
    ],
    10 => [
        'name' => 'Indigo Profesyonel',
        'primary' => '#4f46e5',
        'primary_hover' => '#6366f1',
        'accent' => '#818cf8',
        'glow' => '#4f46e5',
    ],
    11 => [
        'name' => 'Teal Modern',
        'primary' => '#0d9488',
        'primary_hover' => '#14b8a6',
        'accent' => '#2dd4bf',
        'glow' => '#0d9488',
    ],
    12 => [
        'name' => 'Rose Yumuşak',
        'primary' => '#e11d48',
        'primary_hover' => '#f43f5e',
        'accent' => '#fb7185',
        'glow' => '#e11d48',
    ],
    13 => [
        'name' => 'Sky Açık Mavi',
        'primary' => '#0284c7',
        'primary_hover' => '#0ea5e9',
        'accent' => '#38bdf8',
        'glow' => '#0284c7',
    ],
    14 => [
        'name' => 'Violet Klasik',
        'primary' => '#6d28d9',
        'primary_hover' => '#7c3aed',
        'accent' => '#8b5cf6',
        'glow' => '#6d28d9',
    ],
    15 => [
        'name' => 'Lime Canlı',
        'primary' => '#65a30d',
        'primary_hover' => '#84cc16',
        'accent' => '#a3e635',
        'glow' => '#65a30d',
    ],
    17 => [
        'name' => 'Koyu Lacivert',
        'primary' => '#1e3a8a',
        'primary_hover' => '#2563eb',
        'accent' => '#3b82f6',
        'glow' => '#1e3a8a',
    ],
    18 => [
        'name' => 'Bordo Şık',
        'primary' => '#7f1d1d',
        'primary_hover' => '#991b1b',
        'accent' => '#b91c1c',
        'glow' => '#7f1d1d',
    ],
    19 => [
        'name' => 'Turkuaz Serin',
        'primary' => '#0e7490',
        'primary_hover' => '#06b6d4',
        'accent' => '#22d3ee',
        'glow' => '#0e7490',
    ],
    20 => [
        'name' => 'Gümüş Modern',
        'primary' => '#64748b',
        'primary_hover' => '#94a3b8',
        'accent' => '#cbd5e1',
        'glow' => '#64748b',
    ],
];
